application: 8risky
version: 2
runtime: python
api_version: 1

handlers:
- url: /cron
  script: main.py
  login: admin
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /datastore
  script: main.py
  login: admin
- url: /view
  script: main.py
  login: admin
- url: .*
  script: main.py

builtins:
  - datastore_admin: on
