// Generated by CoffeeScript 1.3.1
(function() {
  ﻿;

  var UpdateTable;

  $('#registry_save').click(function() {
    var checks, num;
    checks = (function() {
      var _i, _len, _ref, _results;
      _ref = $('#registry .reg:checked');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        num = _ref[_i];
        _results.push(num.value);
      }
      return _results;
    })();
    UpdateTable({
      'registry': checks.join(',')
    });
    return $('.cc_clear').click();
  });

  $('#country_save').click(function() {
    var checks, num;
    checks = (function() {
      var _i, _len, _ref, _results;
      _ref = $('#country .cc:checked');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        num = _ref[_i];
        _results.push(num.value);
      }
      return _results;
    })();
    UpdateTable({
      'country': checks.join(',')
    });
    return $('.reg_clear').click();
  });

  UpdateTable = function(data) {
    return $.getJSON('/json', data, function(json) {
      var count, i, str, _i, _j, _len;
      str = "";
      for (_i = 0, _len = json.length; _i < _len; _i++) {
        i = json[_i];
        str += "<tr>";
        str += "<td>" + escape(i.registry) + "</td>";
        str += "<td>" + escape(i.country) + "</td>";
        str += "<td>" + escape(i.StartIP) + "</td>";
        str += "<td>" + escape(i.EndIP) + "</td>";
        str += "</tr>";
      }
      $("#viewbar tbody").html(str);
      count = Math.ceil(json.length / 100.0);
      str = "";
      for (i = _j = 1; 1 <= count ? _j <= count : _j >= count; i = 1 <= count ? ++_j : --_j) {
        str += '<li><a href="#">' + i + '</a></li>';
      }
      $("#view_pages ul").html(str);
      return $('#view_pages li:first').attr('class', 'active');
    });
  };

  $('#country .cc').click(function() {
    if ($('.cc_all').attr('checked')) {
      return $('.cc_all').removeAttr('checked');
    }
  });

  $('.reg_all').click(function() {
    if (this.checked) {
      return $('#registry input').attr('checked', 'checked');
    } else {
      return $('#registry input').removeAttr('checked');
    }
  });

  $('.cc_all').click(function() {
    if (this.checked) {
      return $('#country input').attr('checked', 'checked');
    } else {
      return $('#country input').removeAttr('checked');
    }
  });

  $('.reg_clear').click(function() {
    return $('#registry input').removeAttr('checked');
  });

  $('.cc_clear').click(function() {
    return $('#country input').removeAttr('checked');
  });

}).call(this);
