application: 8risky
version: 3
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cron
  script: main.application
  login: admin

- url: /datastore
  script: main.application
  login: admin

- url: /json
  script: main.application

- url: /jsoncustom
  script: main.application

- url: /search
  script: main.application

- url: /bootstrap
  static_dir: bootstrap

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /less
  static_dir: less

- url: /img
  static_dir: img

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
  - remote_api: on
