exec = (require 'child_process').exec

FILES_COFFEE = [
    'js/index.coffee',
    'js/custom.coffee'
]
FILES_LESS = [
    'css/style.less',
    'css/custom.less'
]

FilePathNoEXT = (filename) ->
    return filename.substr(0, filename.lastIndexOf("."))

task 'compile', 'compile js and css.', (options) ->
    outputErr = (err, stdout, stderr) ->
        throw err if err
        if stdout or stderr
            console.log "#(stdout) #(stderr)"

    # LESS
    for file in FILES_LESS
        NOEXT_CSS = FilePathNoEXT(file)
        exec "lessc #{file} > #{NOEXT_CSS}.css", outputErr
        exec "yui-compressor --type css --charset UTF-8 -o #{NOEXT_CSS}.min.css #{NOEXT_CSS}.css", outputErr

    # Coffee Script
    for file in FILES_COFFEE
        NOEXT_JS = FilePathNoEXT(file)
        exec "coffee -c #{file}", outputErr
        exec "compiler --js_output_file #{NOEXT_JS}.min.js --js #{NOEXT_JS}.js", outputErr
